Repository GSG-G13/Abeer-Alaa-API, pull requests merged in 2023-03, with the labels that each got.

#2 file-structure
  index.html
  indexFiles/index.js
  indexFiles/style.css
  spaceFiles/space.js
  spaceFiles/spase.html
  spaceFiles/style.css
Labels: Waiting Review

#8 Add the request function
  spaceFiles/space.js
Labels: done

#9 add get data from api Relates#6
  spaceFiles/space.js
Labels: Waiting Review

#11 edit file structure Relates#10
  img/error.png
  img/logo.jpg
  img/logos.jpg
  img/slide1.webp
  img/slide2.webp
  img/slide3.webp
  img/slide4.webp
  spaceFiles/space.html
Labels: done

#12 hompe page Relates#3
  index.html
  indexFiles/index.js
  indexFiles/style.css
Labels: done

#14 add styling Relates#13
  spaceFiles/space.html
  spaceFiles/space.js
  spaceFiles/style.css
Labels: done

#15 Travel api functions
  spaceFiles/space.html
  spaceFiles/space.js
Labels: approve

#17 edit styling Relates#16
  .vscode/settings.json
  index.html
  indexFiles/index.js
  indexFiles/style.css
Labels: done

#18 styling The Secande API
  img/404.png
  spaceFiles/space.js
  spaceFiles/style.css
Labels: Waiting Review

#21 Edit style to space page
  img/v.png
  spaceFiles/space.js
  spaceFiles/style.css
Labels: Waiting Review

#25 Edit home styling
  img/calendar.png
  img/logoSpace.png
  img/logoo
  img/spaceLogo
  index.html
  indexFiles/style.css
  spaceFiles/space.html
  spaceFiles/space.js
  spaceFiles/style.css
Labels: done

#26 Edit style
  img/v.png
  img/ve.png
  index.html
  indexFile/index.js
  indexFile/style.css
  indexFiles/index.js
  indexFiles/style.css
  spaceFiles/space.html
Labels: done

#28 add error 400 fetch api Relates#27
  img/400 Error Bad Request.png
  img/error (2).png
  img/errorStatus
  index.html
  indexFile/index.js
  indexFile/style.css
Labels: done

#30 Add The Search Function
  img/dlogo.jpg
  index.html
  indexFile/index.js
  indexFile/style.css
Labels: done

#33 refactor Relates#31
  indexFile/index.js
Labels: Waiting Review

#34 Add Responsive
  img/404.png
  img/error (2).png
  img/error.png
  img/errorStatus
  img/logo.jpg
  img/logoSpace.png
  img/logoo
  img/logos.jpg
  img/slide1.webp
  img/slide2.webp
  img/slide3.webp
  img/slide4.webp
  img/spaceLogo
  index.html
  indexFile/style.css
Labels: done

#40 Readme file
  README.md
Labels: done

#42 edit readme file
  README.md
Labels: done

#44 fix background
  index.html
  indexFile/style.css
Labels: approve
